# Based on https://github.com/best-of-lists/best-of/blob/main/.github/workflows/setup-best-of-list.yml
name: setup-best-of-list

on:
  workflow_dispatch:

env:
  DEFAULT_BRANCH: "main"
  SETUP_BRANCH: "setup"
  PLACEHOLDER_REPO: "best-of-lists/best-of-template"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  setup-best-of-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: create-update-branch
        uses: peterjgrainger/action-create-branch@v4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.SETUP_BRANCH }}
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ env.SETUP_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup-template
        shell: bash
        env:
          PLACEHOLDER_REPO: ${{ env.PLACEHOLDER_REPO }}
        run: |
          echo "$GITHUB_REPOSITORY"
          rm -rf history config latest-changes.md README.md projects.yaml ./.github/workflows/setup-best-of-list.yml CONTRIBUTING.md create-best-of-list.md
          mkdir -p ./config
          cp ./template/footer.md ./config/footer.md
          cp ./template/header.md ./config/header.md
          cp ./template/projects.yaml ./projects.yaml
          cp ./template/CONTRIBUTING.md ./CONTRIBUTING.md
          rm -rf ./template/
          sed -i "s:${PLACEHOLDER_REPO}:${GITHUB_REPOSITORY}:g" ./config/footer.md
          sed -i "s:${PLACEHOLDER_REPO}:${GITHUB_REPOSITORY}:g" ./config/header.md
          sed -i "s:${PLACEHOLDER_REPO}:${GITHUB_REPOSITORY}:g" ./CONTRIBUTING.md
          placeholder_name="${PLACEHOLDER_REPO##*/}"
          repo_name="${GITHUB_REPOSITORY##*/}"
          sed -i "s:${placeholder_name}:${repo_name}:g" ./config/header.md
      - name: push-update
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ env.SETUP_BRANCH }}
          commit_user_name: best-of setup
          commit_user_email: actions@github.com
          commit_message: Initial setup for best-of list
          skip_dirty_check: true
          commit_options: "--allow-empty"
      - name: create-pull-request
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE: ${{ env.DEFAULT_BRANCH }}
          HEAD: ${{ env.SETUP_BRANCH }}
        run: |
          set -e
          gh pr create \
            --base "$BASE" \
            --head "$HEAD" \
            --title "Initial setup for best-of list" \
            --body "To finish this setup: select **Merge pull request** below and **Confirm merge**." \
            || true
      - name: sync-labels
        # Alternative actions:
        # https://github.com/crazy-max/ghaction-github-labeler
        # https://github.com/EndBug/label-sync
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: ".github/labels.yml"
          prune: true
